OpenApi, some changes code
golova1337/Rent-a-car pull request #2
Opened 2024-01-17 10:45 UTC by golova1337

i created the file OpenApi.yaml in folder ReadMe

2024-01-17 11:36 UTC, zpwebbear requested changes
Чудово! Я там коментик написав, сподіваюсь все зрозуміло пояснив що робити і чому.

2024-01-17 11:36 UTC, zpwebbear commented on BD/GetAllCarsBd.js
>          const queryGetAllCars = "SELECT * FROM cars Where in_renting = 0 AND is_deleted = 0"
Раз ти вже взяв Knex, то і будемо його далі використовувати для того щоб ходити в базу даних, але то в наступних ітераціях

2024-01-17 11:36 UTC, zpwebbear commented on ReadMe/OpenApi.yaml
> +openapi: "3.0.2"
Це ти ручками цей файл написав? Якщо так, то прям моя повага такій праці. Мені навіть буде дійсно сумно тебе просити переробити цей підхід на інший. Зараз поясню.

Те що ти зробив то є супер, але у цього підходу є маленьке але - файл спеки відірваний від коду. І дуже легко зробити зміни в коді та забути за оновлення спеки. Тому прибігають до більш практичних речей як то генерація цієї специфікації. Ось приклад пакетику https://www.npmjs.com/package/express-openapi який буде тобі генерувати цю спеку з того що ти опишеш в кожному endpoint handler.

Або от щось таке типу яке саме намагаєтсья згенерувати https://www.npmjs.com/package/express-oas-generator. Або от штука яка генерує по схемі валідації https://www.npmjs.com/package/@comparaonline/openapi-generator

Тоді у тебе кожен ендпоінт має свій опис в коді і відповідно коли ти змінюєш код, то ти з більшою вірогідністю зміниш схему. А пакетик тобі то все автоматично перегенерує.

2024-01-19 09:48 UTC, golova1337 commented on ReadMe/OpenApi.yaml
> +openapi: "3.0.2"
я тріжки запутався в цьому завданні. Я зара прікреплю зарзок чи такий тип розвязку ті маєш на увазі.
/**
 * @swagger
 * /api/users/{userId}:
 *   get:
 *     summary: Получить информацию о пользователе по его идентификатору
 *     parameters:
 *       - in: path
 *         name: userId
 *         required: true
 *         schema:
 *           type: string
 *         description: Идентификатор пользователя
 *     responses:
 *       200:
 *         description: Успешный запрос, возвращается информация о пользователе
 *       404:
 *         description: Пользователь не найден
 */
app.get('/api/users/:userId', (req, res) => {
    const userId = req.params.userId;
    // Ваш код для получения информации о пользователе по userId
  
    // Пример ответа
    if (userFound) {
      res.status(200).json({ userId, name: 'John Doe', email: 'john@example.com' });
    } else {
      res.status(404).json({ error: 'Пользователь не найден' });
    }
  });

2024-01-19 09:49 UTC, golova1337 commented on ReadMe/OpenApi.yaml
> +openapi: "3.0.2"
я тріжки запутався в цьому завданні. Я зара прікреплю зарзок чи такий тип розвязку ті маєш на увазі.
робити такі коментаріі для кожного поинта
/**
 * @swagger
 * /api/users/{userId}:
 *   get:
 *     summary: Получить информацию о пользователе по его идентификатору
 *     parameters:
 *       - in: path
 *         name: userId
 *         required: true
 *         schema:
 *           type: string
 *         description: Идентификатор пользователя
 *     responses:
 *       200:
 *         description: Успешный запрос, возвращается информация о пользователе
 *       404:
 *         description: Пользователь не найден
 */

2024-01-19 09:50 UTC, DanilShk commented on ReadMe/OpenApi.yaml
> +openapi: "3.0.2"
ти таке маєш на увазі рішення. Робити опис для кожного єндпоинта?

/**
  @swagger
  /api/users/{userId}:
    get:
      summary: Получить информацию о пользователе по его идентификатору
    parameters:
        - in: path
          name: userId
          required: true
          schema:
            type: string
          description: Идентификатор пользователя
      responses:
        200:
          description: Успешный запрос, возвращается информация о пользователе
        404:
          description: Пользователь не найден
 */

2024-01-22 08:55 UTC, zpwebbear commented on ReadMe/OpenApi.yaml
> +openapi: "3.0.2"
Так, щось типу того. Більш детально вже в телеграм ми обговорили

2024-01-23 11:35 UTC, zpwebbear requested changes
Додай mysql папочку в гітігнор будь ласка і можна буде мержити.

2024-01-23 11:35 UTC, zpwebbear commented on mysql/auto.cnf
> +[auto]
Оці файли треба додати до gitignore. Нам не треба зберігати базу даних в гіті

2024-01-23 16:19 UTC, zpwebbear approved these changes
Approved

2024-01-23 16:32 UTC, merged