rest api => model Users, Cars. Modified => tables
golova1337/Rent-a-car pull request #4
Opened 2024-02-29 12:30 UTC by golova1337

2024-03-06 13:23 UTC, zpwebbear requested changes
Дуже багато зробив всього. Ти зараз на правильному шляху, але треба буде ще пофіксати деякі речі. Виправляй прям в цьому пул реквесті - тобто фіксай, і пуш нові коміти в цю гілку.

2024-03-06 13:23 UTC, zpwebbear commented on app.js
> +const cars = require("./reference/routers/routerCars/routerCars.js");
Тут краще називати прям `carsRouter` або якось так, щоб одразу розуміти що воно таке

2024-03-06 13:23 UTC, zpwebbear commented on reference/controller/controllerCars.js
> + * /car/admin/creation-car:
Якщо ми робимо REST API то нам не треба робити окремо роути для адмінів, а окремо для інших. Можливість "постукати" на цей роут повинна визначатися на рівні автенифікації/авторизації. Тобто 
якщо не адмін ломиться на `POST /cars` то ми просто зарубаємо його на рівні авторизації. Де ту авторизацію робити це вже питання. В твоєму випадку мабуть краще в мідлварі

2024-03-06 13:23 UTC, zpwebbear commented on reference/controller/controllerCars.js
> + * /car/admin/:id:
Та сама штука з видаленням

2024-03-06 13:23 UTC, zpwebbear commented on reference/controller/controllerCars.js
Якщо я правильно зрозумів то ти створив директорію `reference` де почав складати оновлену імплементацію. Тоді вже краще називати вкладені директорії в множині - тобто `models`, `cars`, `views` тощо. 

І щодо назви самого файла - є деякі конвенції які дозволяють більш менш гранулярно візуально розділяти файли. Наприклад замінити `controllerCars.js` на `Cars.controller.js`. Відповідно у тебе буде `Car.model.js` (ну якщо буде). Я розумію що у тебе по суті це не зовсім контроллер, а набір хендлерів-функцій, і тому логічно називати цей файл з маленької літери. Але краще не починати зі слова `controller` бо коли у тебе їх буде багато, то буде важко візуально, бо ми ж читаємо зліва на право.

2024-03-06 13:23 UTC, zpwebbear commented on reference/db/migrations/20240103105058_create_table_cars.js
> +    table.enu("status", ["in_rent", "not_in_rent", "deleted"]).notNullable().defaultTo("not_in_rent");
Гарне рішення!

2024-03-06 13:23 UTC, zpwebbear commented on reference/db/migrations/20240103124531_create_table_rentals.js
> +  return knex.schema.createTable("lease", (table) => {
У тебе назва файлу `create_table_rentals`  а таблиця називається `lease` :grin: Не консистентно вигляда

2024-03-06 13:23 UTC, zpwebbear commented on reference/middleware/jwt/checkJwt.js
> +    req.payload = payload;
Ідея правильна, але зазвичай треба класти не в Payload, а в request додають обєкт користувача прям в якому є всі необхідні штуки для того щоб прям перевірити ролі і багато всього.  

Щось накшталт
```js
req.user = user;
```

2024-03-06 13:23 UTC, zpwebbear commented on reference/middleware/jwt/checkJwt.js
> +    if (!req.payload || req.payload.role !== role) {
Тут треба розділити. Бо якщо немає `payload` то це одне, це означає, що цій перевірці не передувала перевірка JWT токена. Це не означає що у нього невідповідна роль

2024-03-06 13:23 UTC, zpwebbear commented on reference/middleware/validator/validatorBody.js
> +  validatoParams: (req, res, next) => {
Помилка в слові `validato`

2024-03-06 13:23 UTC, zpwebbear commented on reference/middleware/validator/validatorBody.js
> +  ValidationResult: (req, res, next) => {
Слідкуй за тим щоб у тебе не було чогось з великої літери, чогось з маленької - все повинно мати порядок

2024-03-06 13:23 UTC, zpwebbear commented on reference/models/modelCar/ModelCar.js
> +    this.carsTable = TABLES.CARS;
Все непогано зробив, але не дуже добре коли у тебе модель оперує двома табличками. Зазвичай моделька -> табличка. І якщо нам тереба зробити декілька дій, то ми і робимо щось таке (зараз буде псєвдоговнокод, так що не зважай)
```js
class LeaseController {
  async create(body){
    const {carId, userId} = body;
    const user = await UserModel.findById(userId);
    const car = await CarModel.findById(carId);
    
    if(!user || !car){
      throw Error('Wrong data')
    }
    
    const lease = await LeaseModel.create({carId, userId});
    
    return lease;
  }
}
```

Або, щоб не загонятися з такими речами в контроллері, то роблять сервіс. Наприклад

```js
class LeaseController {
  async create(body){
    const {carId, userId} = body;
    
    const lease = await CreateLeaseService.run({carId, userId});
    
    return lease;
  }
}
```

І ось в тому сервісі як раз і оперують всіма модельками та іншим добром. 

Раджу почитати про два патерна які бувають модельки - https://www.thoughtfulcode.com/orm-active-record-vs-data-mapper/ В цілому це більше стосується саме ORM, але в обох випадках модель оперує тільки однією сутністю, ніколи не двума

2024-03-06 13:23 UTC, zpwebbear commented on reference/models/modelUsers/ModelUser.js
> +    this.userPasswordsTable = TABLES.USER_PASSWORDS;
У модельки можуть бути Relations. Ну тобто пов'язані таблиці. І в цьому випадку можна зробити це так як ти зробив. Бо по суті таблиця  UserPasswords  нікуди не дінеться.

Краще ці штуки назначати не в конструкторі, а в полях класу типу 

```js
class UserModel extends BaseModel {
  userTable = TABLES.USERS;
  userPasswordTable = TABLES.USER_PASSWORDS;
  
  constructor(dbConnection){
    super(dbConnection);
  }
}
```

2024-03-06 13:23 UTC, zpwebbear commented on reference/routers/routerAutho/routerUsers.js
> +router.post("/superadmin/creation-admin", checkJwt, checkRole("superadmin"), validator.validtoBodyCreateAdmin, validator.ValidationResult, createAdmin);
Дивись, у тебе в додатку є одна сутність User у якої декілька ролей. Типу суперадмін, адмін та користувач. Так от і ендпоінт так само повинен бути один -  `/users`
Але тобі треба в мідлварках перевіряти - якщо це суперадмін хоче створити User з роллю admin, то все ок, а якщо хтось інший, то не ок.

Так само всі ці штуки вони не стосуються авторизації - ти поклав їх у routerAutho, хоча це просто операції з користувачем.

Ось приклад того як це може виглядати
```js
// Отримання всіх користувачів
router.get('/users', checkRoles(['admin', 'superadmin'], UserController.all);
// Створення користувачів - наприклад супер може створювати всіх, а адмін тільки користувачів.
function checkCreateUsersMiddleware(req, res, next) {
  const {role} = req.body;
  if(role === 'admin' && req.user.role !== 'superadmin'){
    res.status(403).send("Forbidden");
  }
  
  if(role === 'superadmin'){
    res.status(403).send("Forbidden")
  }
  
  if(!['admin', 'superadmin'].includes(req.user.role){
    res.status(403).send("Forbidden")
  }
  
  next()
} 

router.post('/users', checkCreateUsersMiddleware, UserController.create)


```

2024-03-06 13:23 UTC, zpwebbear commented on reference/routers/routerCars/routerCars.js
> +cars.get("/filtration", checkJwt, checkRole("user"), getFilteredCars);
Filtration повинна у тебе бути як частина `/cars` - просто за рахунок queryParameters. Це не повинен бути окремий ендпоінт. Ось подивись приклад як написано в статті. Непогано доречі написано і як раз  express як приклад https://www.geeksforgeeks.org/how-to-implement-search-and-filtering-in-a-rest-api-with-node-js-and-express-js/

2024-03-07 08:08 UTC, golova1337 commented on reference/middleware/jwt/checkJwt.js
> +    if (!req.payload || req.payload.role !== role) {
тоді таке запитання, чи є сенс робити перевірку !req.payload якщо в нас перед нею завжди йде перевірка jwt і якщо він не існує чи не проходить verify то ми його не пускаємо далі. Це просто може бути зайва перевірка.

2024-03-12 18:06 UTC, zpwebbear reviewed
Я там спочатку накидав коментарів про Cars, а зовсім забув що ти казав про те що робив Users. Але ті коментарі релевантні і ти можеш їх почитати, зайвим не буде.

Стосовно Users - ти на вірному шляху, не зовсім то куди я тебе направляв, але ти сам допер до непоганого рішення.

2024-03-12 18:06 UTC, zpwebbear commented on reference/controllers/Cars.controller.js
> +const CarsModel = require("../models/carModel/Car.model");
Ось тут ти називаєш змінну `CarsModel` але імпортуєш її з файлу `Car.model.js`. Не думай що я доколупуюся до дрібниць, це просто кидається в очі. Якщо ми кажемо про модель в коді то вона завжди в однині. Навідміну від назви таблиці в SQL базі в цьому випадку яка буде завжди в множині. Наприклад `CarModel` або навіть просто `Car` але таблиця в базі даних `cars` та ендпоінт також називається `/cars`

2024-03-12 18:06 UTC, zpwebbear commented on reference/controllers/Cars.controller.js
> + * /cars/creation-car:
Тут знову трошечки забагато. Дивись, за прості дії типу Create Read Update Delete треба просто використовувати HTTP методи та ідентифікатори сутності.

Наприлклад

Створення машини `POST /cars`
Отримання массиву машин `GET /cars`
Отримання массиву машин але наприклад з пошуком по назві `GET /cars?search=mazd` або навіть більш досконало `GET /cars?search=brand:maz` (але в цьому випадку треба і бекенд писати більш складний, ми до цього дойдемо)
Отримання однієї машини `GET /cars/:id` - де `:id` це ідентифікатор машини, той самий id з бази даних
Оновлення даних про машину `PUT /cars/:id` або можна використовувати PATCH
Видалення машини `DELETE /cars/:id`

2024-03-12 18:06 UTC, zpwebbear commented on reference/controllers/Cars.controller.js
> + * /cars/lease:
Ось тут можна також зупинитися на загальному `GET /cars?in_rent=true` і в такому випадку тобі не треба окремий ендпоінт для того щоб реалізувати подібну функіональність. Але в цьому випадку треба зробити доволі універсальну модельку. Ось приблизний приклад на псевдокоді

```js

// Function to retrieve cars with filters
async function getCars(filters) {
  let query = db('cars');  // Start with the base cars table

  // Apply filters based on query parameters
  if (filters.in_rent !== undefined) {
    query = query.where('in_rent', filters.in_rent);
  }
  if (filters.brand !== undefined) {
    query = query.where('brand', filters.brand);
  }

  // Return the filtered cars
  return await query.select('*');
}

const app = express();

// Route handler for GET /cars with filters
app.get('/cars', async (req, res) => {
  const filters = req.query;  // Get filters from query parameters
  try {
    const cars = await getCars(filters);
    res.json(cars);  // Send filtered cars as JSON response
  } catch (error) {
    console.error(error);
    res.status(500).send('Error retrieving cars');  // Handle errors
  }
});
```

2024-03-12 18:06 UTC, zpwebbear commented on reference/controllers/Users.controller.js
> +   * /signUp:
Воно начебто і логічно зробити `/signUp` частиною функціональності User, але насправді це частина функціональності Аутентифікація. Наразі то не критично, потім можна буде поправити, або взагалі залишити.

2024-03-12 18:06 UTC, zpwebbear commented on reference/services/usersService/Admin.user.service.js
> +    this.adminUserData = new AdminUserData(this.knex);
Ось це ти зробив прям непогано. Це з величезною натяжкою можна назвати паттерн Repository. Але те що ти до цього допер сам це прям файно, я радий.

2024-03-12 18:06 UTC, zpwebbear commented on reference/services/usersService/Admin.user.service.js
> +    await this.adminUserData.deleteUserBD(id);
Тільки от з іменуванням треба буде ще попрацювати. Якщо ще з `adminUserData` ще ми розберемося, то от в `deleteUserBD` заві точно є `BD` та і `user` також. І не треба розділяти на `AdminUserAccess` та `UserAccess`. То все повинно бути в одному `UserAccess` якщо слідувати твоїій термінології.

2024-03-12 18:06 UTC, zpwebbear commented on reference/services/usersService/User.service.js
> +  async singUp(name, lastname, email, password, role) {
Намагайся робити таким чином щоб методи приймали об'єкт а не параметри по порядку. Поперше ти зможеш в роутері зробити просто 
```js
const body = request.body;
const result = await userService.signUp({...body, role: "user"}); 
```
Це набагато простіше. І в майбутньому тобі не треба буде пам'ятати який параметр де по порядку а ще розширювати - додавати нові параметри і все таке.

2024-03-12 18:06 UTC, zpwebbear commented on reference/services/usersService/User.service.js
> +      const result = await this.userDataAccess.insertNewUser(name, lastname, email, hash, role);
Тут також можна просто обійтися  `this.userDataAccess.insert(userData);`

2024-03-12 18:06 UTC, zpwebbear commented on reference/services/usersService/User.service.js
> +    return { id, token };
Зазвичай айдішку не повертають. Просто токен в якому закодована айдішка. Ємейл кодувати не можна, це палево - якщо хтось прочитає токен який вже протух, то зможе отримати ємейл користувача.

2024-03-12 18:06 UTC, zpwebbear commented on reference/routers/routerAutho/Users.router.js
> +users.post("/registration", validator.validtorBodySingUP, validator.validationResult, ControllerUsers.signUp);
Якщо ти називаєш роут `/registration`  то вже і в контроллері метод називай `registration` ))))

2024-03-12 18:06 UTC, zpwebbear commented on reference/routers/routerAutho/Users.router.js
> +users.get("/all-users", checkJwt, checkRole("admin"), ControllerUsers.getAllUsers);
Тут не треба  `/all-users` - тут просто `GET /` . По аналогії з тим як я писав там вище про Cars router.

2024-03-12 18:06 UTC, zpwebbear commented on reference/routers/routerAutho/Users.router.js
> +users.delete("/:id", checkJwt, checkRole("admin"), validator.validatorParamsId, validator.validationResult, ControllerUsers.deletedUser);
Оце ось правильно!

2024-03-12 18:06 UTC, zpwebbear commented on reference/routers/routerAutho/Users.router.js
> +users.post("/creation-admin", checkJwt, checkRole("superadmin"), validator.validtorBodyCreateAdmin, validator.validationResult, ControllerUsers.createAdmin);
Тут також не треба `/creation-admin` просто `POST /` і все.

2024-03-12 18:06 UTC, zpwebbear commented on reference/routers/routerAutho/Users.router.js
> +users.post("/login", validator.validtorBodyLogin, validator.validationResult, ControllerUsers.login);
Логін та реєстрацію я би виніс в Auth.router

2024-03-12 18:06 UTC, zpwebbear commented on reference/middlewares/jwt/jwt.js
> +    if (req.user.role !== role) {
Ось в таких випадках краще передавати ролі як массив, бо наприклад якась дія повинна бути доступна і суперадміну і адміну також. І потім перевіряти ось так

```js
const checkRole = (roles) => {
  return (req, res, next) => {
    if(roles.includes(req.user.role){
      next()
    }else{
      return res.status(403).json({ message: "sufficient privileges" });
    }
  }
}
```

2024-03-23 13:28 UTC, zpwebbear reviewed
Дуже круто! Молодець!

2024-03-23 13:28 UTC, zpwebbear commented on reference/db/repository/Auth.repository.js
> +  insert(body) {
Описуй і це так як асинхронну функцію, бо вона ж насправді асинхронна

2024-03-23 13:28 UTC, zpwebbear commented on reference/db/repository/Auth.repository.js
> +  async checkByEmail(email) {
Це ж не чек, це `getByEmail`

2024-03-23 13:28 UTC, zpwebbear commented on reference/db/repository/Car.repository.js
> +  async checkActiveLease(id) {
Якщо ти називаєш метод `checkActiveLease` то повертай вже  boolean. Ну типу `true` або `false`. Ну це звісно якщо тобі там далі не треба з цим об'єктом машинки працювати

2024-03-23 13:28 UTC, zpwebbear commented on reference/db/repository/User.repository.js
> +const { knex } = require("../config/connection");
Розділяй порожним рядочком імпорти та сам код. Це так, стале правило

2024-03-23 13:28 UTC, zpwebbear commented on reference/db/repository/User.repository.js
> +      deleted_at: date,
В цьому випадку можна залишити просто `deleted_at`, тобі не треба тримати ще окремий флаг `is_deleted`. А якщо тобі треба наприклад вибрати всіх юзерів які не видалені ти просто додаєш `WHERE deleted_at is NULL` Ну і відповідно поле `deleted_at` потрібно зробити nullable.

2024-03-23 13:28 UTC, zpwebbear commented on reference/helpers/auth/password.js
> +  if (!result) throw new Error("Password is incorrect");
Я б з хелпера помилку б не викидав. Краще повернути просто true або false і потім вже на рівні сервісу вирішувати, чи то помилку викинути чи ще щось

2024-03-23 13:28 UTC, zpwebbear commented on reference/helpers/jwt/jwt.helper.js
> +class JwtHelper {
Чудово!

2024-03-23 13:28 UTC, zpwebbear commented on reference/routers/auth.router.js
> +author.post("/", userValidator.singUP, userValidator.validationResult, authController.signUp);
Так а чого роут просто `/`? Назви його також `/signup` 

Ну зазвичай в апішках ці роути розташовані на урлах типу  `https://example.com/api/auth/signup`

2024-03-23 13:28 UTC, zpwebbear commented on reference/routers/cars.router.js
> +// повернення авто тільки адміном (чому не просто по id а через reclaim бо в майбутньому може буде обнова данних авто)
Гарний коментар. Зрозуміло

2024-03-23 13:28 UTC, zpwebbear commented on reference/services/User.service.js
> +      return {
А чого ти в `Car.service` не повертав ось таких об'єктів? Насправді це гарна практика мати стандартизовану відповідь від API. Ну ось наприклад:

Якщо все ок
```js
{
  status: true,
  data: {}, // тут от пхаєш сюди відповідь
  meta: {}, // якісь дані наприклад про пагінацію, типу { page: 1, total: 20 }
  errors: {} // тут помилки віддавати, якщо наприклад помилок немає то просто порожній об'єкт чи false
}
```

Але якщо прям ще глибше копнути це відповідальність фреймворка, або транспортного шару. Тобто твій сервіс зараз знає про формат апішки і це порушує Single Responsibility Principle -  коли твій код повинен мати тільки одну причину для змін. А у тебе зараз тут цих причин щонайменше 2. Що я маю на увазі - якщо зміниться логіка по якій ти будеш виймати юзерів, з бази, то треба буде переписувати код, і якщо наприклад тобі доведеться переписувати структуру відповіді, то тобі так само треба буде переписувати твій сервіс.

Я раджу винести формування структури щонайменше в контроллер, і так само зробити фабрику `ApiResponse` в яку ти будеш передавати тільки необхідні дані і воно вже буде створювати все що треба.

Приклад 

```js
class ApiResponseFactory {
  static createResponse({data, meta: {}}){
     return {
       status: true,
       data,
       meta,
       errors: {}
     }
  }
  
  static createErrorResponse({errors}){
    return {
      status: false,
      data: {},
      meta: {},
      errors
    }
  }
}

class CarController {
  async get(id){
    try{
      const car = await CarService.getById(id);
      return ApiResponseFactory.createResponse({data: car})
    } catch (e) {
      return ApiResponseFactory.createErrorResponse({errors: e})
    }
  }
}
```


Ну це я прям для прикладу накидав. Насправді помилки ти можеш обробляти десь в мідлварі. Або так само формувати об'єкт відповіді також в мідлварі. Але я показав для розуміння.

UPDATE: я побачив що в останньому файлі ти вже зробив свій Response. Але все одно про всяк випадок залишу цей комент як є.

2024-03-23 13:28 UTC, zpwebbear commented on reference/utils/response.js
> +class Responses {
Оооооо, так ти це вже і зробив. Крутяк

2024-03-27 06:10 UTC, zpwebbear requested changes
Для тих 1-2 місяців що ти працюєш, це дуже гарний результат. Воно майже бездоганно для рівня джуна. Розслаблятися рано, але все виглядає дуже рівномірно і коли читаєш код відчувається що ти повноцінно розумієш те що ти робиш. 

Так, там підшліфувати треба місцями. Перенести дещо в контроллер (ось ті формування об'єктів відповіді, бо сервіс не повинен про них знати).

2024-03-27 06:10 UTC, zpwebbear commented on reference/db/repository/User.repository.js
> +    const result = await this.knex(TABLES.USERS).returning("create_at").insert({
Тут у тебе скоріш за все помилка в `created_at`.

2024-03-27 06:10 UTC, zpwebbear commented on reference/db/repository/User.repository.js
> +  async delete(id, date) {
Я розумію чого ти передаєш дату з сервісу, ну наче для того щоб відділити логіку від репозиторію. І це правильний підхід, але в цьому випадку, так як у тебе `deleted_at` це за бізнес логікою завжи час коли видалили, то можна прям в query builder передавати `now` так як ось тут написано https://knexjs.org/guide/utility.html#now. 

І в твоєму випадку це буде виглядати наступним чином:

```js
await this.knex(TABLES.USERS).where({ id: id }).update({
  deleted_at: knex.fn.now()
});
```

2024-03-27 06:10 UTC, zpwebbear commented on reference/helpers/Auth.helpers.js
> +class authHelpers {
Чудово що ти зробив окремий клас для хелперів. Але тут можна ще трошечки покращити.
1. Назвати клас з великої літери `AuthHelper`, в однині, бо це у тебе вже не набір хелперів а один клас.
2. Так як ти не користуєшся `this` в середині методів, то можна зробити всі методи статичними і щоб ти в подальшому працював не з екземпляром класу, а просто з методами. Пам'ятаєш як у тебе на початку був якийсь контролер зроблений?


Ці зауваження не критичні, можна і так як є (але з великої літери все ж назвати :grin: )

2024-03-27 06:10 UTC, zpwebbear commented on reference/middlewares/validator/user.validator.js
> +        const user = await authorService.getByEmail(value);
Тут також краще бути консистентним. Якщо у тебе є `auth` роут та контроллер, хай вже буде і `authService`

2024-03-27 06:10 UTC, zpwebbear commented on reference/controllers/Auth.controller.js
> +      const { message, data, meta } = await AuthService.login({ ...body, ...user });
А для чого ти тут користувача передаєш в `AuthService.login`? Він же ще не залогінений і тобі з нього жодної користі.

2024-03-27 06:10 UTC, zpwebbear commented on reference/services/Car.service.js
> +    return {
Я писав в минулому пул реквесті, що ось це от формування відповіді повинно відбуватися в контроллері. 

Можна зробити окремий шар Transformers, які будуть перетворювати те що віддає сервіс в те що буде віддаватися користувачу по HTTP. Наскільки це воно буде тобі зараз потрібно, я не знаю. Але те що ці об'єкти не повинні бути в сервісі то точно

2024-03-27 06:10 UTC, zpwebbear commented on reference/services/Car.service.js
> +    const { paginatedResult, totalPages } = pagination(page, perPage, result);
Пагінація повиина працювати на рівні бази даних. Це повиинен бути сформований запит, бо уяви собі що у тебе є 1 000 000 машинок в базі даних. В твоєму випадку ти вивантажиш їх усих в пам'ять і будеш там робити обчислення і це буде дуже боляче.

Ось непоганий хоч і перевантажений приклад https://github.com/avanelli/fastify-realworld-example-app/blob/bdb8ce4e130916a76970d8df1bf1a3291d0f5227/lib/models/articles.js#L29C5-L29C16

Ось плагінчик який може тобі допомогти https://www.npmjs.com/package/knex-paginate

А ось просто стаття щоб почитати як воно робиться https://trycatchdebug.net/news/1138597/postgresql-pagination-knex-js

2024-03-27 07:43 UTC, golova1337 commented on reference/controllers/Auth.controller.js
> +      const { message, data, meta } = await AuthService.login({ ...body, ...user });
так ми створюемо jwt token за payload {id,role}, порівнюємо паролі ті що він прислав і той хеш що у нас в бд. Може я щось не так зрозумів?

2024-04-04 05:01 UTC, zpwebbear approved these changes
Great job!

2024-04-04 05:01 UTC, zpwebbear commented on Readme.md
> +2. Execute: git clone https://github.com/golova1337/Rent-a-car.git
Чудово що ти прям так заморочився з документацією. Для того щоб показати частинку коду, або наприклад команду в терміналі файно використовувати ось таку штуку https://docs.github.com/get-started/writing-on-github/working-with-advanced-formatting/creating-and-highlighting-code-blocks#fenced-code-blocks

Тоді воно буде виглядати ось так 

2. Execute:
```bash
git clone https://github.com/golova1337/Rent-a-car.git
```

2024-04-04 05:01 UTC, zpwebbear commented on reference/db/repository/Car.repository.js
> +  async get(pagination, filters) {
Чудово!

2024-04-04 05:01 UTC, zpwebbear commented on reference/utils/paginationCal.js
> +function paginationCal({ data, page, perPage, count }) {
А чого така дивна назва? :grin:

2024-04-04 07:24 UTC, merged